PApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('plan.urls')),
    url(r'^admin/', admin.site.urls),
]

plan/urls.py
from django.conf.urls import url
from . import views

app_name = 'plan'
urlpatterns = [
	# regex, view, kwargs, name
	url(r'^$', views.index, name='index'),
	url(r'^project/(?P<project_id>[0-9]+)/(?P<time>[0-9]+)/$', views.project, name='project'),
	url(r'^create/project/$', views.create_project, name='create_project'),
	url(r'^submit/project/$', views.submit_project, name='submit_project'),
	url(r'^edit/project/(?P<project_id>[0-9]+)/$', views.edit_project, name='edit_project'),
	url(r'^delete/project/$', views.delete_project, name='delete_project'),
	url(r'^task/(?P<task_id>[0-9]+)/(?P<time>[0-1]+)/$', views.task, name='task'),
	url(r'^create/task/project/(?P<project_id>[0-9]+)/staff/(?P<staff_id>[0-9]+)/$', views.create_task, name='create_task'),
	url(r'^edit/task/(?P<task_id>[0-9]+)/project/(?P<project_id>[0-9]+)/staff/(?P<staff_id>[0-9]+)/$', views.edit_task, name='edit_task'),
	url(r'^delete/task/$', views.delete_task, name='delete_task'),
	url(r'^submit/task/$', views.submit_task, name='submit_task'),
	url(r'^staff/(?P<staff_id>[0-9]+)/$', views.staff, name='staff'),
	url(r'^calendar/all/$', views.calendar_page, name='calendar'),
	url(r'^calendar/project/(?P<project_id>[0-9]+)/$', views.calendar_project, name='calendar_project'),
	url(r'^calendar/staff/(?P<staff_id>[0-9]+)/$', views.calendar_staff, name='calendar_staff'),
]

plan/models.py
import datetime

from django.db import models
from django.utils import timezone

class Department(models.Model):
	name = models.CharField(max_length=200)
	def __str__(self):
		return self.name

	def staff(self):
		staff = Staff.objects.filter(dep = self).filter(active = True)
		return staff

class Stream(models.Model):
	name = models.CharField(max_length=200)
	def __str__(self):
		return self.name

	def projects(self):
		projects = Project.objects.filter(stream = self)
		return projects

class Staff(models.Model):
	name = models.CharField(max_length=200)
	dep = models.ForeignKey(Department, db_index=True, on_delete=models.CASCADE)
	active = models.BooleanField(db_index=True, default = True)

	def __str__(self):
		return self.name

	def projects(self):
		today = datetime.date.today()
		projects = Project.objects.filter(task__staff = self).filter(task_start_date__lte = today).filter(task_end_date__gte = today)
		return {'project': projects, 'num_projects': len(projects)}

class Project(models.Model):
	name = models.CharField(max_length=200)
	stream = models.ForeignKey(Stream, db_index=True, on_delete=models.SET_NULL, null = True)
	dates = models.BooleanField(default = False) #False means that actual tasks are needed to calculate start & end dates. True will take default values if they exist.
	task_start_date = models.DateField(null = True)
	task_end_date = models.DateField(null = True)
	start_date = models.DateField(null = True)
	end_date = models.DateField(null = True)
	active = models.BooleanField(db_index=True, default = True)
	comment = models.CharField(max_length=500, null=True) #let us comment the project and what it is supposed to achieve
	update = models.DateTimeField(default = timezone.now())

	def __str__(self):
		return self.name

	def start(self):
		if self.task_start_date:
			s = self.task_start_date
		else : s = self.start_date
		return s

	def tasks(self):
		if len(Task.objects.filter(project_id = self.id).filter(active = True)) > 0: return len(Task.objects.filter(project_id = self.id).filter(active = True))
		else: return False

	def end(self):
		if self.task_end_date:
			e = self.task_end_date
		else : e = self.end_date
		return e

	def days(self):
		if self.task_start_date and self.task_end_date:
			days = ((self.task_end_date - self.task_start_date) / datetime.timedelta(days = 1) + 1)
		else : days = ((self.end_date - self.start_date) / datetime.timedelta(days = 1) + 1)
		return int(days)

	def weeks(self):
		if self.task_start_date and self.task_end_date:
			weeks = round(((self.task_end_date - self.task_start_date) / datetime.timedelta(days = 1) + 1.0) / 7.0, 1)
		else: weeks = round(((self.end_date - self.start_date) / datetime.timedelta(days = 1) + 1.0) / 7.0, 1)
		return weeks

class Task(models.Model):
	name = models.CharField(max_length=200)
	staff = models.ForeignKey(Staff, db_index=True, on_delete=models.SET_NULL, null=True)
	worker = models.CharField(max_length=200, null=True) #this is in case the task is performed not by staff, but by someone outside of the company, e.g. certification
	project = models.ForeignKey(Project, db_index=True, on_delete=models.CASCADE)
	start_date = models.DateField(db_index=True)
	end_date = models.DateField(db_index=True)
	done = models.DecimalField(default = 0, max_digits=5, decimal_places=2, null=True) #to store percent of completion of the task.
	comment = models.CharField(max_length=500, null=True)
	active = models.BooleanField(db_index=True, default = True)
	update = models.DateTimeField(default = timezone.now())

	def __str__(self):
		return "%s by %s " % (self.name, self.staff)

	def start(self):
		return self.start_date

	def end(self):
		return self.end_date

	def days(self):
		return int((self.end_date - self.start_date) / datetime.timedelta(days = 1) + 1)

	def weeks(self):
		return round(((self.end_date - self.start_date) / datetime.timedelta(days = 1) + 1.0) / 7.0, 1)

class Holiday(models.Model):
	date = models.DateField(db_index=True)
	holiday = models.BooleanField(default = True)
	def __str__(self):
		return str(self.date)

# Create your models here.

plan/views.py
import datetime
import math
import calendar
import sys
from django.utils import timezone
from .gen_cal import get_project_context
from .gen_cal import get_project_tasks
from .gen_cal import get_project_plan
from .gen_cal import get_projects
from .gen_cal import get_tasks
from .gen_cal import get_week_tasks_context, get_lines_tasks_context
from .gen_cal import get_date_selection
from .gen_cal import ProjectDates
from .gen_cal import SetCal
from .plan_function import calendar_context, project_calendar_context, dashboard_context, project_task_dates, week_start, week_end

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.views import generic
from django.template import loader
from django.shortcuts import redirect
from .models import Staff, Department, Project, Task, Stream


def index(request):
	try:
		cal_setting = request.POST['cal_setting']
	except KeyError:
		cal_setting = 'this_week'
	else:
		cal_setting = request.POST['cal_setting']

	context = {'today': datetime.date.today(), 
				'dashboard': dashboard_context(show_empty = True, group_dash = 'department'), 
				'alt_cal': calendar_context(start = cal_setting, days_in_line = 35, num_lines = 2, obj = False, obj_id = False, group = 'department', row = 'staff', show_empty = True), 
				'staff_list' : Department.objects.all(), 
				'project_list': Stream.objects.all(), 
				'cal_setting': cal_setting, 
				'project_cal': project_calendar_context(start = datetime.date.today().replace(month = 1, day = 1)),}
	return render(request, 'plan/index.html', context)

def project(request, project_id, time):
	#project_task_dates()
	try:
		project = Project.objects.get(pk=project_id)
	except (KeyError, Project.DoesNotExist):
		project = False
		return HttpResponse("Failed to find project with ID'%s'! Try again." % project_id)

	if project:
		try:
			cal_setting = request.POST['cal_setting']
		except KeyError:
			cal_setting = 'this_week'
		else:
			cal_setting = request.POST['cal_setting']
		
		context = {'project': project, 'today': datetime.date.today(), 
					'dashboard': dashboard_context(project = project.id, obj = project, obj_id = project.id, show_empty = False, group_dash = 'department'), 
					'alt_cal': calendar_context(start = cal_setting, days_in_line = 35, num_lines = 2, obj = False, obj_id = False, group = 'department', row = 'staff', show_empty = True, project = project.id), 
					'staff_list' : Department.objects.all(), 
					'project_list': Stream.objects.all(), 
					'cal_setting': cal_setting,
					'calendar': calendar_context(start = 'all', days_in_line = int((week_end(project.end()) - week_start(project.start())) / datetime.timedelta(days=1) + 1), num_lines = 1, obj = project, obj_id = project.id, group = 'department', row = 'task', show_empty = False, project = project),}
		return render(request, 'plan/project.html', context)

def task(request, task_id, time):
	task = Task.objects.get(pk=task_id)
	context = {'task': task, 
				'days': int((task.end_date - task.start_date + datetime.timedelta(days=1)) / datetime.timedelta(days=1)),
				'staff_list' : Department.objects.all(), 
				'project_list': Stream.objects.all(),
				'time': int(time), 
				'timestamp': timezone.now().timestamp(),
				'today': datetime.date.today(),
				}
	return render(request, 'plan/task.html', context)

def staff(request, staff_id):
	staff = Staff.objects.get(pk = staff_id)
	if len(Task.objects.filter(active=True, staff_id = staff_id)) > 0:
		s = SetCal(datetime.date.today())
		try:
			cal_setting = request.POST['cal_setting']
		except KeyError:
			cal_setting = 'this_week'
		else:
			cal_setting = request.POST['cal_setting']
		data = get_project_context(0, staff=staff_id, start=s.start(cal_setting))
		t = []
		for p in Project.objects.all():
			a = p.task_set.filter(staff_id = staff_id, active = True).count()
			b = p.task_set.filter(staff_id = staff_id, active = True)
			if a > 0:
				t.append({'project': p, 'task_count': a, 'tasks' : b,})
		context = {'today': datetime.date.today(), 
					'staff': staff,
					'project_cal': project_calendar_context(start = datetime.date.today().replace(month = 1, day = 1), staff = staff_id),
					'alt_cal': calendar_context(start = cal_setting, days_in_line = 35, num_lines = 2, obj = staff, obj_id = int(staff_id), group = 'stream', row = 'project', show_empty = True),
					'dashboard': dashboard_context(staff = staff.id, obj = staff, obj_id = staff.id, show_empty = False, group_dash = 'stream', row='project'),
					'staff_list' : Department.objects.all(), 
					'project_list': Stream.objects.all(), 
					'task_count' : t, 
					'lines': data['lines'], 
					'row_names': data['row_names'], 
					'rows': data['rows'], 
					'cal_setting': cal_setting,}
	else:
		context = {'today': datetime.date.today(), 'staff_list' : Department.objects.all(), 'project_list': Stream.objects.all(), 'staff': staff, }

	return render(request, 'plan/staff.html', context)

def create_project(request):
	context = {'staff_list' : Department.objects.all(), 
				'project_list': Stream.objects.all(), 
				'stream_list': Stream.objects.all(),
				'date': get_date_selection(),
				'edit': False,
				'today': datetime.date.today(),
				}
	return render(request, 'plan/create_project.html', context)

def edit_project(request, project_id):
	project = Project.objects.get(pk = project_id)
	selected = {'project': project, 
				'name': project.name,
				'stream': project.stream,
				'comment': project.comment,
				'start_date': project.start(),
				'end_date': project.end(),
				'task_num': project.tasks(),}

	context = {'project_list' : Stream.objects.all(), 
				'staff_list' : Department.objects.all(),
				'stream_list': Stream.objects.all(),
				'date': get_date_selection(),
				'selected': selected, 
				'edit': project.id, 
				'timestamp': timezone.now().timestamp(),
				'today': datetime.date.today(),
				}
	
	return render(request, 'plan/create_project.html', context)

def create_task(request, project_id, staff_id):
	p_id = int(project_id)
	s_id = int(staff_id)

	s = SetCal(datetime.date.today())
	try:
		cal_setting = request.POST['cal_setting']
	except KeyError:
		cal_setting = 'this_week'
	else:
		cal_setting = request.POST['cal_setting']

	if request.GET.get('comment', False) : comment = request.GET.get('comment', False)
	else: comment = False

	if request.GET.get('name', False) : name = request.GET.get('name', False)
	else: name = False

	if request.GET.get('sday', False) and request.GET.get('smonth', False) and request.GET.get('syear', False): 
		start_date = {'day': False, 'month': False, 'year': False}
		try: start_date['day'] = int(request.GET.get('sday', False))
		except ValueError: start_date['day'] = False
		try: start_date['month'] = int(request.GET.get('smonth', False))
		except ValueError: start_date['month'] = False
		try: start_date['year'] = int(request.GET.get('syear', False))
		except ValueError: start_date['year'] = False
		if start_date['year']:
			if not start_date['year'] >= datetime.date.today().year: start_date['year'] = False
		if start_date['month']:
			if not (start_date['month'] >= 1 and start_date['month'] <= 12): start_date['month'] = False
		if start_date['day'] and start_date['day'] > 0 and start_date['day'] < 32:
			if start_date['month'] and start_date['year'] and not (start_date['day'] <= calendar.monthrange(start_date['year'], start_date['month'])[1]):
				start_date['day'] = calendar.monthrange(start_date['year'], start_date['month'])[1]
		else: start_date['day'] = False
	else: start_date = {'day': False, 'month': False, 'year': False}

	if request.GET.get('eday', False) and request.GET.get('emonth', False) and request.GET.get('eyear', False): 
		end_date = {'day': False, 'month': False, 'year': False}
		try: end_date['day'] = int(request.GET.get('eday', False))
		except ValueError: end_date['day'] = False
		try: end_date['month'] = int(request.GET.get('emonth', False))
		except ValueError: end_date['month'] = False
		try: end_date['year'] = int(request.GET.get('eyear', False))
		except ValueError: end_date['year'] = False
		if end_date['year']:
			if not end_date['year'] >= datetime.date.today().year: end_date['year'] = False
		if end_date['month']:
			if not (end_date['month'] >= 1 and end_date['month'] <= 12): end_date['month'] = False
		if end_date['day'] and end_date['day'] > 0 and end_date['day'] < 32:
			if end_date['month'] and end_date['year'] and not (end_date['day'] <= calendar.monthrange(end_date['year'], end_date['month'])[1]):
				end_date['day'] = calendar.monthrange(end_date['year'], end_date['month'])[1]
		else: end_date['day'] = False
	else: end_date = {'day': False, 'month': False, 'year': False}

	selected = {'project': False, 
				'staff': False, 
				'project_lines': False, 
				'staff_lines' : False,
				'name': name, 'comment': comment,
				'start_date': start_date,
				'end_date': end_date,
				}
	if p_id > 0:
		selected['project'] = Project.objects.filter(pk = p_id)[0]
		if selected['project'].task_set.filter(active=True).count() > 0:
			selected['project_lines'] = get_project_context(p_id, start=s.start(cal_setting))
			selected['project_lines_new'] = calendar_context(start = 'all', days_in_line = 35, num_lines = False, obj = selected['project'], obj_id = p_id, group = 'department', row = 'staff', show_empty = True, project = p_id)
	if s_id > 0:
		selected['staff'] = Staff.objects.filter(pk = s_id)[0]
		if selected['staff'].task_set.filter(active=True).count() > 0:
			selected['staff_lines_new'] = calendar_context(start = cal_setting, days_in_line = 35, num_lines = 2, obj = Staff.objects.filter(pk = s_id)[0], obj_id = int(s_id), group = 'stream', row = 'project', show_empty = True)

	context = {'today': datetime.date.today(),
				'staff_list' : Department.objects.all(), 
				'project_list': Stream.objects.all(),
				'project_select' : Project.objects.filter(active=True), 

plan/templates/plan/create_project.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'plan/style.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'plan/style2.css' %}"/>
{% if edit and selected.project%}
<div id="delete_window">
	<div class="delete_wrapper">
		<form action="{% url 'plan:delete_project' %}" method="post">
		{% csrf_token %}
		<input style="display: none" type="text" name="name" value="{{ selected.project.name }}"/>
		<input style="display: none" type="text" name="edit" value="{{ selected.project.id }}"required/>
		<input style="display: none" type="text" name="delete" value="{{ selected.project.id }}"required/>
		<input style="display: none" type="text" name="timestamp" value="{{ timestamp }}" required/>
		<div class="regular" style="width: 100%; text-align: center; font-size: 15px;">
			<span class="bold">All {{ selected.task_num }} tasks</span> in the <span class="bold">{{ selected.project.name }}</span> will also be deleted.</br></br>Are you sure you would like to delete this project?</div>
		<div class="header" style="width: 180px; left: 48px; margin-top: 30px; margin-bottom: 20px;">
			<div class="header_logo header_menu header_create" style="width: 60px; margin-right: 60px;" onclick="getElementById('delete_window').style.display='none'">
				<div class="header_title">NO</div>
			</div>
			<div class="header_logo header_menu header_delete" style="width: 60px; margin: 0; padding: 0;">
				<input class="header_title button" type="submit" value="YES" />
			</div>
		</div>
		</form>
	</div>
</div>
{% endif %}
<div class="header">
	<div class="header_logo">
		<a href="{% url 'plan:index' %}"><img class="logo" src="{% static 'plan/images/logo_uma.png' %}"/></a>
		<div class="logo_text bold">Planning</div>
	</div>
	<div class="header_logo header_menu">
		<div class="header_title regular">Projects</div>
		<ul class="header_dropbox">
			{% if project_list %}
				{% for stream in project_list %}
					<li class="header_dropbox_titlerow regular">{{ stream.name }}</li>
					{% for project in stream.projects %}
						<a href="{% url 'plan:project' project.id 0 %}"><li class="header_dropbox_row">{{ project.name }}</li></a>
					{% endfor %}
				{% endfor %}
			{% endif %}
		</ul>
	</div>
	<div class="header_logo header_menu" style="margin-right: 70px;">
		<div class="header_title regular">Staff</div>
		<ul class="header_dropbox">
			{% if staff_list %}
				{% for dep in staff_list %}
					<li class="header_dropbox_titlerow regular">{{ dep.name }}</li>
					{% for staff in dep.staff %}
						<a href="{% url 'plan:staff' staff.id %}"><li class="header_dropbox_row">{{ staff.name }}</li></a>
					{% endfor %}
				{% endfor %}
			{% endif %}
		</ul>
	</div>
	<a href="{% url 'plan:create_project' %}">
		<div class="header_logo header_menu header_create">
			<div class="header_title regular">Create Project</div>
		</div>
	</a>
	<a href="{% url 'plan:create_task' 0 0 %}">
		<div class="header_logo header_menu header_create" style="margin-right: 70px;">
			<div class="header_title regular">Create Task</div>
		</div>
	</a>
	<div class="header_logo header_date">
		<div class="logo_text bold">{{ today|date:"j F Y" }}</div>
	</div>
</div>
<div class="page_object_header" style="border-color: #12bb2a;">
	<h3 class="bold page_object_header_section"></h3>
	<h1 class="bold page_object_header_section">{% if edit %}Edit Project{% else %}Create New Project{% endif %}</h1>
	<h3 class="bold page_object_header_section"></h3>
</div>
{% if errors.error %}
<div class="input_warning_box">
    <div class="input_warning_box_title bold">Warning! Data was not saved!</div>
	{% for error in errors.texts %}
		{% if error.text %}
		<ul>
	        <li class="regular" style="margin-top: 5px;">{{ error.location }}:</li>
	        {% for t in error.text %}
	        	<li class="light">{{ t }}</li>
	        {% endfor %}
	    </ul>
	    {% endif %}
	{% endfor %}
</div>
{% endif %}

<form action="{% url 'plan:submit_project' %}" method="post">
{% csrf_token %}
<div class="form_section">
	<input class="form_style{% if errors.name %} input_error{% endif %}" type="text" name="name" placeholder="project title" {% if selected.name %}value="{{ selected.name }}"{% endif %}/>
	</br>
	</br>
	{% if stream_list %}
	<select class="form_style{% if errors.stream %} input_error{% endif %}" id="st_select" name="stream" required >
		{% if not edit and not selected.stream %}
		<option value="0">Select stream</option>
		{% endif %}
		{% for stream in stream_list %}
			<option value="{{ stream.id }}" {% if selected.stream and selected.stream.id == stream.id %}selected="selected"{% endif %}>{{ stream.name }}</option>
		{% endfor %}
	</select>
	{% endif %}
</div>
<div class="form_section">
{% if not selected.project.tasks %}
	<div class="form_style_date_title">Select start date:</div>
	<select class="form_style form_style_date{% if errors.start_date %} input_error{% endif %}" name="start_date_day" required>
		<option>Date</option>
		{% for d in date.dates %}
			<option value="{{ d }}" {% if selected.start_date.day == d %}selected="selected"{% endif %}>{{ d }}</option>
		{% endfor %}
	</select>
	<select class="form_style form_style_date{% if errors.start_date %} input_error{% endif %}" name="start_date_month" required>
		<option>Month</option>
		{% for m in date.months %}
			<option value="{{ m.num }}" {% if selected.start_date.month == m.num %}selected="selected"{% elif not selected.start_date.month and today.month == m.num %}selected="selected"{% endif %}>{{ m.str }}</option>
		{% endfor %}
	</select>
	<select class="form_style form_style_date{% if errors.start_date %} input_error{% endif %}" name="start_date_year" required>
		<option>Year</option>
		{% for y in date.years %}
			<option value="{{ y }}" {% if selected.start_date.year == y %}selected="selected"{% elif not selected.start_date.year and today.year == y %}selected="selected"{% endif %}>{{ y }}</option>
		{% endfor %}
	</select>
	<br />
	<div class="form_style_date_title">Select end date:</div>
	<select class="form_style form_style_date{% if errors.end_date %} input_error{% endif %}" name="end_date_day" required>
		<option>Date</option>
		{% for d in date.dates %}
			<option value="{{ d }}" {% if selected.end_date.day == d %}selected="selected"{% endif %}>{{ d }}</option>
		{% endfor %}
	</select>
	<select class="form_style form_style_date{% if errors.end_date %} input_error{% endif %}" name="end_date_month" required>
		<option>Month</option>
		{% for m in date.months %}
			<option value="{{ m.num }}" {% if selected.end_date.month == m.num %}selected="selected"{% elif not selected.end_date.month and today.month == m.num %}selected="selected"{% endif %}>{{ m.str }}</option>
		{% endfor %}
	</select>
	<select class="form_style form_style_date{% if errors.end_date %} input_error{% endif %}" name="end_date_year" required>
		<option>Year</option>
		{% for y in date.years %}
			<option value="{{ y }}" {% if selected.end_date.year == y %}selected="selected"{% elif not selected.end_date.year and today.year == y %}selected="selected"{% endif %}>{{ y }}</option>
		{% endfor %}
	</select>
	<br />
	<br />
{% elif selected.project.tasks %}
	<div class="form_style_date_title light">Project dates based on active tasks</div>
	<div class="form_style_date_title">Start date:</div>
	<div class="form_style_date_title bold">{{ selected.project.start|date:"j F Y" }}</div>
	<div class="form_style_date_title">End date:</div>
	<div class="form_style_date_title bold">{{ selected.project.end|date:"j F Y" }}</div>
{% endif %}
</div>
<div class="form_section">
	<textarea class="form_style form_style_textarea{% if errors.comment %} input_error{% endif %}" rows=5 cols=30 name="comment" placeholder="Project description (not required)">{% if selected.comment != null %}{{ selected.comment }}{% endif %}</textarea>
</div>
<br/>
<br/>
<input style="display: none" type="text" name="edit" {% if edit and selected.project %}value="{{ selected.project.id }}"{% else %}value="0" {% endif %}required/>
<input style="display: none" type="text" name="timestamp" {% if edit and selected.project %}value="{{ timestamp }}"{% else %}value="0" {% endif %}required/>

<div class="header" style="clear: both; height: auto; overflow: hidden;">
	<div class="button_wrap" style="{% if edit and selected.project %}width: 500px; margin-left: -250px;{% else %}width: 152px; margin-left: -61px;{% endif %}">
		<div class="header_logo header_menu header_create" style="padding: 0;">
			<input class="header_title regular button" type="submit" value="{% if edit %}Save {% else %}Create {% endif %}Project" />
		</div>
		{% if edit and selected.project %}
			<a href="{% url 'plan:project' selected.project.id 0 %}">
				<div class="header_logo header_menu header_edit">
					<div class="header_title regular button">Cancel</div>
				</div>
			</a>
			<div class="header_logo header_menu header_delete" onclick="getElementById('delete_window').style.display='block'">
				<div class="header_title regular">Delete Project</div>
			</div>
		{% endif %}
	</div>
</div>

</form>


<div class="lists_wrapper">
	<div class="list">
		<h3>Active Projects:</h3>
		{% if project_list %}
		<ul>
			{% for stream in project_list %}
			<li class="bottom_list_title bold">{{ stream.name }}</li>
				{% for project in stream.projects %}
					<li><a class="bottom_list_link" href="{% url 'plan:project' project.id 0 %}">{{ project.name }}</a></li>
				{% endfor %}
			{% endfor %}
		</ul>
	</div>
	<div class="list">
		{% endif %}
		<h3>Staff:</h3>
		{% if staff_list %}
		<ul>
			{% for dep in staff_list %}
			<li class="bottom_list_title bold">{{ dep.name }}</li>
				{% for staff in dep.staff %}
					<li><a class="bottom_list_link" href="{% url 'plan:staff' staff.id %}">{{ staff.name }}</a></li>
				{% endfor %}
			{% endfor %}
		</ul>
		{% endif %}
	</div>
</div>

plan/templates/plan/submit_project.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'plan/style.css' %}"/>

<h2>New Project "{{ project.name }}" has been successfully created!</h2>

<p><a href="{% url 'plan:create_task' %}">Create tasks for project "{{ project.name }}"</a></p>
<p><a href="{% url 'plan:create_project' %}">Edit project "{{ project.name }}"</a></p>
<p><a href="{% url 'plan:create_project' %}">Create another project</a></p>

<form action="{% url 'plan:submit_project' %}" method="post">
{% csrf_token %}
<input type="text" name="name" placeholder="project title"/>
<br />
<br />
<input type="submit" value="Create Project" />
</form>